"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { configured, supabase } from "@/lib/supabase";

type Room={id:string;code:string;host_id:string;status:string;day_number:number};
type Player={id:string;room_id:string;user_id:string;name:string;role:string|null;alive:boolean;seat:number};
type Action={id:number;room_id:string;player_id:string;day_number:number;action_type:string;target_id:string|null;submitted:boolean};
const roles=["임프","독살범","수도승","점쟁이","공감자","장의사","요리사","처녀","군인","시장"];
const needsTarget=(role:string|null)=>["임프","독살범","수도승","점쟁이"].includes(role||"");
const roleHelp:Record<string,string>={"임프":"오늘 밤 공격할 플레이어를 선택하세요.","독살범":"오늘 밤 중독시킬 플레이어를 선택하세요.","수도승":"오늘 밤 보호할 다른 플레이어를 선택하세요.","점쟁이":"오늘 밤 조사할 플레이어를 선택하세요."};

export default function Home(){
 const [userId,setUserId]=useState(""); const [room,setRoom]=useState<Room|null>(null); const [me,setMe]=useState<Player|null>(null);
 const [players,setPlayers]=useState<Player[]>([]); const [actions,setActions]=useState<Action[]>([]); const [name,setName]=useState(""); const [code,setCode]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const isHost=!!room&&room.host_id===userId;
 const load=useCallback(async(roomId:string)=>{if(!supabase)return; const [{data:r},{data:p},{data:a}]=await Promise.all([supabase.from("rooms").select("*").eq("id",roomId).single(),supabase.from("room_players").select("*").eq("room_id",roomId).order("seat"),supabase.from("actions").select("*").eq("room_id",roomId)]); if(r)setRoom(r); if(p){setPlayers(p);setMe(p.find(x=>x.user_id===userId)||null)} if(a)setActions(a)},[userId]);
 useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(async({data})=>{let id=data.session?.user.id;if(!id){const {data:d,error:e}=await supabase!.auth.signInAnonymously();if(e){setError("익명 접속 설정이 필요합니다.");return}id=d.user?.id}if(id)setUserId(id)});},[]);
 useEffect(()=>{if(!room||!supabase)return; const client=supabase; load(room.id); const ch=client.channel(`room-${room.id}`).on("postgres_changes",{event:"*",schema:"public",table:"rooms",filter:`id=eq.${room.id}`},()=>load(room.id)).on("postgres_changes",{event:"*",schema:"public",table:"players",filter:`room_id=eq.${room.id}`},()=>load(room.id)).on("postgres_changes",{event:"*",schema:"public",table:"actions",filter:`room_id=eq.${room.id}`},()=>load(room.id)).subscribe(); return()=>{client.removeChannel(ch)}},[room?.id,load]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"오류가 발생했습니다.")}finally{setBusy(false)}};
 const create=()=>run(async()=>{if(!supabase||!userId)throw Error("서버 연결을 확인해 주세요.");if(!name.trim())throw Error("이름을 입력하세요.");const roomCode=Math.random().toString(36).slice(2,8).toUpperCase();const {data:r,error:e}=await supabase.from("rooms").insert({code:roomCode,host_id:userId,status:"lobby",day_number:1}).select().single();if(e)throw e;const {data:p,error:pe}=await supabase.from("players").insert({room_id:r.id,user_id:userId,name:name.trim(),seat:1}).select().single();if(pe)throw pe;setRoom(r);setMe(p)});
 const join=(e:FormEvent)=>{e.preventDefault();run(async()=>{if(!supabase||!userId)throw Error("서버 연결을 확인해 주세요.");if(!name.trim()||code.trim().length!==6)throw Error("이름과 6자리 방 코드를 입력하세요.");const {data:r,error:re}=await supabase.from("rooms").select("*").eq("code",code.trim().toUpperCase()).single();if(re||!r)throw Error("방을 찾을 수 없습니다.");const {count}=await supabase.from("players").select("*",{count:"exact",head:true}).eq("room_id",r.id);if((count||0)>=10)throw Error("참가 인원이 가득 찼습니다.");const {data:p,error:pe}=await supabase.from("players").upsert({room_id:r.id,user_id:userId,name:name.trim(),seat:(count||0)+1},{onConflict:"room_id,user_id"}).select().single();if(pe)throw pe;setRoom(r);setMe(p)});};
 const assign=()=>run(async()=>{if(!supabase||!room) return; const shuffled=[...roles].sort(()=>Math.random()-.5);for(let i=0;i<players.length;i++){const {error:e}=await supabase.from("players").update({role:shuffled[i]}).eq("id",players[i].id);if(e)throw e}await supabase.from("rooms").update({status:"day"}).eq("id",room.id)});
 const phase=(status:string)=>run(async()=>{if(!supabase||!room)return;const nextDay=status==="day"&&room.status==="night"?room.day_number+1:room.day_number;const {error:e}=await supabase.from("rooms").update({status,day_number:nextDay}).eq("id",room.id);if(e)throw e});
 const submit=(target:string)=>run(async()=>{if(!supabase||!room||!me)return;const {error:e}=await supabase.from("actions").upsert({room_id:room.id,player_id:me.id,user_id:userId,day_number:room.day_number,action_type:me.role||"확인",target_id:target||null,submitted:true},{onConflict:"room_id,player_id,day_number"});if(e)throw e});
 const mine=actions.find(a=>a.player_id===me?.id&&a.day_number===room?.day_number); const submitted=new Set(actions.filter(a=>a.day_number===room?.day_number&&a.submitted).map(a=>a.player_id));
 if(!configured)return <main className="shell"><Header/><section className="card"><h2>서버 연결 준비 중</h2><p>배포 환경 변수를 연결하면 방 생성과 실시간 동기화가 활성화됩니다.</p></section></main>;
 if(!room)return <main className="shell"><Header/><section className="hero"><p className="eyebrow">모두의 밤 행동을 한 화면에</p><h1>시계탑을 더 빠르고<br/>조용하게 진행하세요.</h1><p>설치 없이 최대 10명이 각자의 스마트폰으로 참여합니다.</p></section><section className="card join"><label>내 이름<input value={name} onChange={e=>setName(e.target.value)} maxLength={12} placeholder="예: 경태"/></label><button className="primary" onClick={create} disabled={busy}>새 게임 만들기</button><div className="divider"><span>또는</span></div><form onSubmit={join}><label>6자리 방 코드<input className="codeInput" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={6} placeholder="ABC123"/></label><button className="secondary" disabled={busy}>게임 참가하기</button></form>{error&&<p className="error">{error}</p>}</section></main>;
 return <main className="shell"><Header/><section className="roomHead"><div><span className="badge">{room.status==="lobby"?"대기실":room.status==="night"?`NIGHT ${room.day_number}`:`DAY ${room.day_number}`}</span><h2>방 코드 <strong>{room.code}</strong></h2></div><span>{players.length}/10명</span></section>
 <section className="card"><div className="sectionTitle"><h3>참가자</h3><span className="live">● 실시간 연결</span></div><div className="players">{players.map(p=><div className={`player ${p.alive?"":"dead"}`} key={p.id}><span className="seat">{p.seat}</span><div><b>{p.name}{p.user_id===userId?" (나)":""}</b>{isHost&&p.role&&<small>{p.role}</small>}</div>{room.status==="night"&&needsTarget(p.role)&&<span className={submitted.has(p.id)?"done":"wait"}>{submitted.has(p.id)?"제출 완료":"대기"}</span>}</div>)}</div>
 {isHost&&room.status==="lobby"&&<button className="primary" disabled={busy||players.length<3} onClick={assign}>역할 배정하고 시작</button>}
 {isHost&&room.status!=="lobby"&&<div className="phaseButtons"><button onClick={()=>phase("day")} disabled={busy||room.status==="day"}>낮 시작</button><button onClick={()=>phase("night")} disabled={busy||room.status==="night"}>밤 시작</button></div>}</section>
 {me?.role&&<section className={`card roleCard ${room.status}`}><p className="eyebrow">나의 캐릭터</p><h2>{me.role}</h2><p>{room.status==="night"?(roleHelp[me.role]||"오늘 밤에는 선택할 행동이 없습니다."):"정체를 다른 사람에게 보여주지 마세요."}</p>{room.status==="night"&&needsTarget(me.role)&&<TargetPicker players={players.filter(p=>p.alive&&!(me.role==="수도승"&&p.id===me.id))} initial={mine?.target_id||""} onSubmit={submit} busy={busy}/>} {mine&&<p className="success">✓ 행동이 제출되었습니다. 다시 제출하면 수정됩니다.</p>}</section>}
 {isHost&&room.status==="night"&&<section className="card"><h3>스토리텔러 종합창</h3>{actions.filter(a=>a.day_number===room.day_number).map(a=>{const actor=players.find(p=>p.id===a.player_id),target=players.find(p=>p.id===a.target_id);return <div className="action" key={a.id}><b>{actor?.name} · {actor?.role}</b><span>→ {target?.name||"선택 없음"}</span></div>})}</section>}{error&&<p className="error floating">{error}</p>}</main>;
}
function TargetPicker({players,initial,onSubmit,busy}:{players:Player[];initial:string;onSubmit:(id:string)=>void;busy:boolean}){const [target,setTarget]=useState(initial);useEffect(()=>setTarget(initial),[initial]);return <div className="targets">{players.map(p=><label key={p.id}><input type="radio" name="target" value={p.id} checked={target===p.id} onChange={()=>setTarget(p.id)}/><span>{p.name}</span></label>)}<button className="primary" disabled={!target||busy} onClick={()=>onSubmit(target)}>행동 제출</button></div>}
function Header(){return <header><div className="mark">CT</div><div><b>CLOCKTOWER</b><span>LIVE</span></div></header>}
