"use client";
import Link from "next/link";
import {FormEvent,PointerEvent,useCallback,useEffect,useRef,useState} from "react";
import {byName,characters,goodRoles} from "@/lib/characters";
import {configured,supabase} from "@/lib/supabase";
import "./modes.css";

type Room={id:string;code:string;host_id:string;status:string;day_number:number;game_mode:"storyteller"|"auto";winner:string|null;nomination_target_id:string|null;phase_ends_at:string|null;dawn_message:string|null};
type Player={id:string;room_id:string;user_id:string;name:string;role:string|null;alive:boolean;seat:number;is_storyteller:boolean;position_x:number|null;position_y:number|null;rmk_role:string|null};
type Action={id:string;room_id:string;actor_player_id:string;day_number:number;phase:string;action_type:string;target_id:string|null;submitted:boolean};
type PlayerNote={target_player_id:string;position_x:number|null;position_y:number|null;rmk_role:string|null};
const roles=characters.map(c=>c.name), needsTarget=(r:string|null)=>["임프","독살범","수도사","점쟁이","집사","까마귀지기"].includes(r||"");
const roleHelp:Record<string,string>={임프:"공격할 플레이어를 선택하세요.",독살범:"중독시킬 플레이어를 선택하세요.",수도사:"보호할 다른 플레이어를 선택하세요.",점쟁이:"조사할 플레이어를 선택하세요.",집사:"내일 투표를 따를 주인을 선택하세요.",까마귀지기:"오늘 밤 사망했다면 확인할 플레이어를 선택하세요."};
const firstNight=[["황혼","모두 눈을 감았는지 확인합니다. 여행자·전설 캐릭터가 있다면 먼저 처리합니다."],["하수인 정보","7명 이상이면 하수인들을 깨워 악마를 알려줍니다."],["악마 정보","7명 이상이면 악마에게 하수인과 미참여 선한 캐릭터 3개를 알려줍니다."],["독살범","플레이어 1명을 선택합니다."],["세탁부","주민 토큰과 후보 플레이어 2명을 확인합니다."],["사서","외지인 토큰과 후보 플레이어 2명을 확인합니다."],["수사관","하수인 토큰과 후보 플레이어 2명을 확인합니다."],["요리사","이웃한 악한 플레이어 쌍의 수를 확인합니다."],["초공감자","양옆 생존자 중 악한 플레이어 수를 확인합니다."],["점쟁이","플레이어 2명을 골라 악마 또는 허상 포함 여부를 확인합니다."],["집사","주인 1명을 선택합니다."],["첩자","마도서를 확인합니다."],["새벽","잠시 기다린 뒤 모두 눈을 뜹니다."]];
const laterNight=[["황혼","모두 눈을 감았는지 확인합니다."],["독살범","플레이어 1명을 선택합니다."],["수도사","다른 플레이어 1명을 보호합니다."],["탕녀","오늘 악마가 되었다면 새 역할을 확인합니다."],["임프","플레이어 1명을 선택합니다. 자신을 선택했다면 생존 하수인이 새 임프가 됩니다."],["까마귀지기","오늘 밤 사망했다면 한 명의 캐릭터를 확인합니다."],["초공감자","양옆 생존자 중 악한 플레이어 수를 확인합니다."],["점쟁이","플레이어 2명을 선택해 결과를 확인합니다."],["장의사","낮에 처형된 플레이어의 캐릭터를 확인합니다."],["집사","주인 1명을 선택합니다."],["첩자","마도서를 확인합니다."],["새벽","모두 눈을 뜨고 밤의 사망자를 알립니다."]];

export default function Home(){
 const [userId,setUserId]=useState(""),[room,setRoom]=useState<Room|null>(null),[me,setMe]=useState<Player|null>(null),[players,setPlayers]=useState<Player[]>([]),[actions,setActions]=useState<Action[]>([]),[notes,setNotes]=useState<PlayerNote[]>([]),[shortened,setShortened]=useState(false),[now,setNow]=useState(Date.now()),[dawnVisible,setDawnVisible]=useState(false),[name,setName]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selectedPlayer,setSelectedPlayer]=useState<string|null>(null);
 const boardRef=useRef<HTMLDivElement>(null),dragRef=useRef<string|null>(null),lastDragRef=useRef<{x:number;y:number}|null>(null),isHost=!!room&&room.host_id===userId;
 const load=useCallback(async(id:string)=>{if(!supabase)return;const[{data:r},{data:p},{data:a},{data:n},{data:s}]=await Promise.all([supabase.from("rooms").select("*").eq("id",id).single(),supabase.from("room_players").select("*").eq("room_id",id).order("seat"),supabase.from("actions").select("*").eq("room_id",id),supabase.from("player_notes").select("target_player_id,position_x,position_y,rmk_role").eq("room_id",id),supabase.from("timer_shortens").select("day_number,phase").eq("room_id",id)]);if(r){setRoom(r);setShortened(!!s?.some(x=>x.day_number===r.day_number&&x.phase===r.status))}if(p){setPlayers(p);setMe(p.find(x=>x.user_id===userId)||null)}if(a)setActions(a);if(n)setNotes(n)},[userId]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(async({data})=>{let id=data.session?.user.id;if(!id){const{data:d,error:e}=await supabase!.auth.signInAnonymously();if(e){setError("익명 접속 설정이 필요합니다.");return}id=d.user?.id}if(id)setUserId(id)})},[]);
 useEffect(()=>{if(!room||!supabase)return;const client=supabase;load(room.id);const ch=client.channel(`room-${room.id}`).on("postgres_changes",{event:"*",schema:"public",table:"rooms",filter:`id=eq.${room.id}`},()=>load(room.id)).on("postgres_changes",{event:"*",schema:"public",table:"players",filter:`room_id=eq.${room.id}`},()=>load(room.id)).on("postgres_changes",{event:"*",schema:"public",table:"actions",filter:`room_id=eq.${room.id}`},()=>load(room.id)).subscribe(),poll=window.setInterval(()=>load(room.id),1500);return()=>{clearInterval(poll);client.removeChannel(ch)}},[room?.id,load]);
 useEffect(()=>{const tick=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(tick)},[]);
 useEffect(()=>{if(room?.status==="day"&&room.dawn_message){setDawnVisible(true);navigator.vibrate?.([180,80,180])}},[room?.dawn_message,room?.status]);
 useEffect(()=>{if(!supabase||!room||room.game_mode!=="auto"||!["day","night"].includes(room.status)||!room.phase_ends_at)return;const remaining=new Date(room.phase_ends_at).getTime()-now;if(remaining<=0)supabase.rpc("advance_auto_phase",{p_room_id:room.id}).then(()=>load(room.id))},[now,room?.id,room?.status,room?.phase_ends_at,room?.game_mode,load]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn()}catch(e){setError(e instanceof Error?e.message:typeof e==="object"&&e&&"message" in e?String(e.message):"오류가 발생했습니다.")}finally{setBusy(false)}};
 const create=()=>run(async()=>{if(!supabase||!userId)throw Error("서버 연결을 확인해 주세요.");if(!name.trim()||name.trim().length>5)throw Error("이름은 1~5글자로 입력하세요.");let roomCode="";for(let i=0;i<8;i++){const candidate=String(Math.floor(1000+Math.random()*9000)),{count}=await supabase.from("rooms").select("*",{count:"exact",head:true}).eq("code",candidate);if(!count){roomCode=candidate;break}}if(!roomCode)throw Error("방 코드를 만들지 못했습니다. 다시 시도해 주세요.");const{data:r,error:e}=await supabase.from("rooms").insert({code:roomCode,host_id:userId,status:"lobby",day_number:1,game_mode:"storyteller"}).select().single();if(e)throw e;const{data:p,error:pe}=await supabase.from("players").insert({room_id:r.id,user_id:userId,nickname:name.trim(),seat_number:1,is_storyteller:true}).select().single();if(pe)throw pe;setRoom(r);setMe(p)});
 const join=(e:FormEvent)=>{e.preventDefault();run(async()=>{if(!supabase||!userId)throw Error("서버 연결을 확인해 주세요.");if(!name.trim()||name.trim().length>5||!/^\d{4}$/.test(code.trim()))throw Error("이름은 최대 5글자, 방 코드는 숫자 4자리입니다.");const{data:r,error:re}=await supabase.from("rooms").select("*").eq("code",code.trim()).single();if(re||!r)throw Error("방을 찾을 수 없습니다.");const{count}=await supabase.from("players").select("*",{count:"exact",head:true}).eq("room_id",r.id);if((count||0)>=16)throw Error("참가 인원이 가득 찼습니다.");const{data:p,error:pe}=await supabase.from("players").upsert({room_id:r.id,user_id:userId,nickname:name.trim(),seat_number:(count||0)+1,is_storyteller:false},{onConflict:"room_id,user_id"}).select().single();if(pe)throw pe;setRoom(r);setMe(p)})};
 const assign=()=>run(async()=>{if(!supabase||!room)return;const playable=players.filter(p=>!p.is_storyteller),assigned=room.game_mode==="auto"&&playable.length===3?["임프",...[...goodRoles].sort(()=>Math.random()-.5).slice(0,2)].sort(()=>Math.random()-.5):[...roles].sort(()=>Math.random()-.5);for(let i=0;i<playable.length;i++){const{error:e}=await supabase.from("players").update({role:assigned[i],alive:true}).eq("id",playable[i].id);if(e)throw e}const seconds=room.game_mode==="auto"?playable.length*30:null,{error:e}=await supabase.from("rooms").update({status:"night",day_number:1,winner:null,dawn_message:null,phase_ends_at:seconds?new Date(Date.now()+seconds*1000).toISOString():null}).eq("id",room.id);if(e)throw e;if(room.game_mode==="auto")await supabase.rpc("advance_auto_phase",{p_room_id:room.id});await load(room.id)});
 const updatePlayer=(id:string,values:Record<string,unknown>)=>run(async()=>{if(!supabase||!isHost)return;const{error:e}=await supabase.from("players").update(values).eq("id",id);if(e)throw e});
 const updateNote=(target:string,values:Partial<PlayerNote>)=>run(async()=>{if(!supabase||!room||!userId)return;const current=notes.find(n=>n.target_player_id===target),next={room_id:room.id,user_id:userId,target_player_id:target,position_x:current?.position_x??null,position_y:current?.position_y??null,rmk_role:current?.rmk_role??null,...values};setNotes(items=>[...items.filter(n=>n.target_player_id!==target),next]);const{error:e}=await supabase.from("player_notes").upsert(next,{onConflict:"room_id,user_id,target_player_id"});if(e)throw e});
 const changeMode=(next:"storyteller"|"auto")=>run(async()=>{if(!supabase||!room||!me||!isHost||room.status!=="lobby")return;const{error:re}=await supabase.from("rooms").update({game_mode:next}).eq("id",room.id);if(re)throw re;const{error:pe}=await supabase.from("players").update({is_storyteller:next==="storyteller",role:null}).eq("id",me.id);if(pe)throw pe;await load(room.id)});
 const move=(e:PointerEvent<HTMLDivElement>)=>{if(!dragRef.current||!boardRef.current)return;const r=boardRef.current.getBoundingClientRect(),x=Math.max(7,Math.min(93,(e.clientX-r.left)/r.width*100)),y=Math.max(9,Math.min(91,(e.clientY-r.top)/r.height*100)),id=dragRef.current;lastDragRef.current={x,y};setNotes(ns=>[...ns.filter(n=>n.target_player_id!==id),{target_player_id:id,position_x:x,position_y:y,rmk_role:ns.find(n=>n.target_player_id===id)?.rmk_role??null}])};
 const stopMove=()=>{const id=dragRef.current,pos=lastDragRef.current;dragRef.current=null;lastDragRef.current=null;if(id&&pos)updateNote(id,{position_x:pos.x,position_y:pos.y})};
 const finish=(winner:"good"|"evil")=>run(async()=>{if(supabase&&room&&isHost)await supabase.from("rooms").update({status:"finished",winner}).eq("id",room.id)}),nominate=(id:string)=>run(async()=>{if(supabase&&room&&isHost)await supabase.from("rooms").update({nomination_target_id:id}).eq("id",room.id)});
 const vote=()=>run(async()=>{if(!supabase||!room||!me||!room.nomination_target_id)return;const{error:e}=await supabase.from("actions").upsert({room_id:room.id,actor_player_id:me.id,user_id:userId,day_number:room.day_number,phase:"day",action_type:"vote",target_id:room.nomination_target_id,submitted:true},{onConflict:"room_id,actor_player_id,day_number"});if(e)throw e});
 const execute=()=>run(async()=>{if(!supabase||!room||!isHost||!room.nomination_target_id)return;const target=players.find(p=>p.id===room.nomination_target_id);if(!target)return;const{error:e}=await supabase.from("players").update({alive:false}).eq("id",target.id);if(e)throw e;const alive=players.filter(p=>p.alive&&!p.is_storyteller&&p.id!==target.id),winner=target.role==="임프"?"good":alive.length<=2?"evil":null;await supabase.from("rooms").update({nomination_target_id:null,...(room.game_mode==="auto"&&winner?{status:"finished",winner}:{})}).eq("id",room.id)});
 const phase=(status:"day"|"night")=>run(async()=>{if(!supabase||!room||!isHost)return;const next=status==="night"&&room.status==="day"?room.day_number+1:room.day_number,{error:e}=await supabase.from("rooms").update({status,day_number:next}).eq("id",room.id);if(e)throw e});
 const submit=(target:string)=>run(async()=>{if(!supabase||!room||!me)return;const{error:e}=await supabase.from("actions").upsert({room_id:room.id,actor_player_id:me.id,user_id:userId,day_number:room.day_number,phase:"night",action_type:me.role||"확인",target_id:target||null,submitted:true},{onConflict:"room_id,actor_player_id,day_number"});if(e)throw e;if(room.game_mode==="auto")await supabase.rpc("advance_auto_phase",{p_room_id:room.id});await load(room.id)});
 const shorten=()=>run(async()=>{if(!supabase||!room)return;const{error:e}=await supabase.rpc("shorten_auto_phase",{p_room_id:room.id});if(e)throw e;setShortened(true);await supabase.rpc("advance_auto_phase",{p_room_id:room.id});await load(room.id)});
 if(!configured)return <main className="shell"><Header/><section className="card"><h2>서버 연결 준비 중</h2></section></main>;
 if(!room)return <main className="shell"><Header/><section className="hero"><p className="eyebrow">Trouble Brewing 진행 도구</p><h1>이야기꾼과 함께,<br/>또는 완전 자동으로.</h1><p>먼저 방을 만들고 대기실에서 진행 방식을 고르세요.</p></section><section className="card join"><label>내 이름 · 최대 5글자<input value={name} onChange={e=>setName(e.target.value)} maxLength={5}/></label><button className="primary" onClick={create} disabled={busy}>새 방 만들기</button><div className="divider"><span>또는 참가</span></div><form onSubmit={join}><label>숫자 4자리 방 코드<input className="codeInput" inputMode="numeric" pattern="[0-9]*" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,4))} maxLength={4}/></label><button className="secondary" disabled={busy}>게임 참가하기</button></form>{error&&<p className="error">{error}</p>}</section></main>;
 const playable=players.filter(p=>!p.is_storyteller),nominee=players.find(p=>p.id===room.nomination_target_id),dayVotes=actions.filter(a=>a.day_number===room.day_number&&a.phase==="day"&&a.target_id===room.nomination_target_id),hasVoted=dayVotes.some(a=>a.actor_player_id===me?.id),majority=Math.floor(playable.filter(p=>p.alive).length/2)+1,mine=actions.find(a=>a.actor_player_id===me?.id&&a.day_number===room.day_number&&a.phase==="night"),submitted=new Set(actions.filter(a=>a.day_number===room.day_number&&a.phase==="night"&&a.submitted).map(a=>a.actor_player_id)),selected=players.find(p=>p.id===selectedPlayer),selectedNote=selected?notes.find(n=>n.target_player_id===selected.id):null,label=room.status==="finished"?`${room.winner==="good"?"선량":"악"} 승리`:room.status==="lobby"?"대기실":room.status==="night"?(room.day_number===1?"첫째 밤":`${room.day_number}일차 밤`):`${room.day_number}일차 낮`,remaining=Math.max(0,Math.ceil(((room.phase_ends_at?new Date(room.phase_ends_at).getTime():now)-now)/1000)),nightRoles=room.day_number===1?["독살범","세탁부","사서","수사관","요리사","초공감자","점쟁이","집사","첩자"]:["독살범","수도사","임프","초공감자","점쟁이","집사","첩자"],hasNightAction=!!me?.role&&nightRoles.includes(me.role);
 return <main className={`shell gameShell ${room.status}`}><Header/>{dawnVisible&&room.dawn_message&&<div className="dawnAlert" role="alert"><span>☀</span><div><b>새벽이 밝았습니다</b><p>{room.dawn_message}</p></div><button onClick={()=>setDawnVisible(false)} aria-label="알림 닫기">×</button></div>}<section className="roomHead"><div><span className="badge">{label}</span><h2>방 코드 <strong>{room.code}</strong></h2><small>{room.game_mode==="storyteller"?"이야기꾼 판정 모드":"자동 진행 모드"}</small></div><span>{playable.length}/15명</span></section>
 {room.game_mode==="auto"&&["day","night"].includes(room.status)&&<section className="card phaseTimer"><div><p className="eyebrow">{room.status==="day"?"DAY TIMER":"NIGHT TIMER"}</p><strong>{String(Math.floor(remaining/60)).padStart(2,"0")}:{String(remaining%60).padStart(2,"0")}</strong><small>{room.status==="day"?`기본 ${playable.length}분 · 개인당 1분 단축`:`기본 ${playable.length*30}초 · 개인당 30초 단축`}</small></div><button className="secondary" disabled={shortened||busy||remaining===0} onClick={shorten}>{shortened?"단축권 사용 완료":room.status==="day"?"1분 단축":"30초 단축"}</button></section>}
 <section className="card townSquare"><div className="sectionTitle"><h3>나의 마을 광장</h3><span className="privateBadge">나만 보임</span></div><p className="fieldHint">토큰을 끌어 내 방식대로 배치하고, 눌러 RMK 역할을 기록하세요.</p>{isHost&&room.status==="lobby"&&<div className="lobbyMode"><p>이번 게임 진행 방식</p><div className="modePick"><button className={room.game_mode==="storyteller"?"selected":""} onClick={()=>changeMode("storyteller")}><b>이야기꾼 모드</b><small>방장이 진행과 판정을 담당</small></button><button className={room.game_mode==="auto"?"selected":""} onClick={()=>changeMode("auto")}><b>자동 모드</b><small>방장도 역할을 받고 플레이</small></button></div></div>}<div className="playerField" ref={boardRef} onPointerMove={move} onPointerUp={stopMove} onPointerCancel={stopMove}><div className="fieldCenter"><b>{label}</b><small>{room.status==="night"?"모두 눈을 감습니다":room.status==="day"?"토론과 투표":"게임 준비"}</small></div>{playable.map((p,i)=>{const a=i/Math.max(playable.length,1)*Math.PI*2-Math.PI/2,note=notes.find(n=>n.target_player_id===p.id),x=note?.position_x??50+Math.cos(a)*39,y=note?.position_y??50+Math.sin(a)*39,mark=note?.rmk_role?byName[note.rmk_role]:null;return <button key={p.id} className={`fieldPlayer ${p.alive?"":"deadToken"} ${selectedPlayer===p.id?"chosen":""}`} style={{left:`${x}%`,top:`${y}%`}} onPointerDown={e=>{dragRef.current=p.id;e.currentTarget.setPointerCapture(e.pointerId)}} onClick={()=>setSelectedPlayer(p.id)}><span className={`tokenPortrait ${mark?"portrait":""}`} style={mark?{backgroundPosition:`${mark.index%6*20}% ${Math.floor(mark.index/6)*33.333}%`}:undefined}>{!mark&&p.seat}</span><b>{p.name}{p.user_id===userId?" · 나":""}</b><small>{note?.rmk_role||(!p.alive?"사망":`좌석 ${p.seat}`)}</small>{room.status==="night"&&needsTarget(p.role)&&<i className={submitted.has(p.id)?"ready":"waiting"}/>}</button>})}</div>
 {selected&&<div className="rmkEditor"><div><b>{selected.name}</b><small>RMK · 내 개인 역할 메모</small></div><select value={selectedNote?.rmk_role||""} onChange={e=>updateNote(selected.id,{rmk_role:e.target.value||null})}><option value="">역할 미지정</option>{characters.map(c=><option key={c.name} value={c.name}>{c.team} · {c.name}</option>)}</select>{isHost&&room.game_mode==="storyteller"&&room.status!=="lobby"&&<button className="mini" onClick={()=>updatePlayer(selected.id,{alive:!selected.alive})}>{selected.alive?"사망 처리":"부활 처리"}</button>}</div>}
 {isHost&&room.status==="lobby"&&<><p className="hint">{room.game_mode==="auto"?"3인 테스트: 악마 1명 + 선량/외지인 2명":"이야기꾼 외 플레이어 5명부터 시작"}</p><button className="primary" disabled={busy||playable.length<(room.game_mode==="auto"?3:5)} onClick={assign}>{room.game_mode==="auto"?"3인 자동 테스트 시작":"역할 배정하고 첫째 밤 시작"}</button></>}{isHost&&room.game_mode==="storyteller"&&!["lobby","finished"].includes(room.status)&&<><div className="phaseButtons"><button onClick={()=>phase("day")} disabled={busy||room.status==="day"}>새벽 · 낮 시작</button><button onClick={()=>phase("night")} disabled={busy||room.status==="night"}>황혼 · 다음 밤</button></div><div className="phaseButtons verdict"><button onClick={()=>finish("good")}>선량 승리 판정</button><button onClick={()=>finish("evil")}>악 승리 판정</button></div></>}</section>
 {me?.role&&<RoleCard role={me.role} roomStatus={room.status}/>} {room.status==="night"&&<NightGuide day={room.day_number}/>} {me?.role&&room.status==="night"&&hasNightAction&&<section className="card nightAction"><h3>{me.role}의 밤 행동</h3>{needsTarget(me.role)?<><p>{roleHelp[me.role]}</p><TargetPicker players={players.filter(p=>p.alive&&!(me.role==="수도사"&&p.id===me.id))} initial={mine?.target_id||""} onSubmit={submit} busy={busy}/></>:<><p>안내받은 정보를 확인했다면 완료를 눌러 주세요.</p><button className="primary" disabled={!!mine||busy} onClick={()=>submit("")}>확인 완료</button></>}{mine&&<p className="success">✓ 이번 밤 행동을 완료했습니다.</p>}</section>}
 {room.status==="day"&&<section className="card voteCard"><p className="eyebrow">낮 진행</p><h3>지목과 투표</h3>{isHost&&<div className="targets">{playable.filter(p=>p.alive).map(p=><button className="secondary" key={p.id} onClick={()=>nominate(p.id)}>{p.name} 지목</button>)}</div>}{nominee?<><p><b>{nominee.name}</b> 님이 지목되었습니다.</p><p>찬성 {dayVotes.length}표 · 처형 기준 {majority}표</p>{me&&!me.is_storyteller&&me.alive&&<button className="primary" disabled={hasVoted||busy} onClick={vote}>{hasVoted?"찬성표 제출 완료":"처형에 찬성"}</button>}{isHost&&<button className="secondary" disabled={dayVotes.length<majority||busy} onClick={execute}>과반수 처형 확정</button>}</>:<p>자유롭게 토론한 뒤 이야기꾼이 지목을 시작합니다.</p>}</section>}{isHost&&room.status==="night"&&<section className="card"><h3>이야기꾼 종합창</h3>{actions.filter(a=>a.day_number===room.day_number).map(a=>{const actor=players.find(p=>p.id===a.actor_player_id),target=players.find(p=>p.id===a.target_id);return <div className="action" key={a.id}><b>{actor?.name} · {actor?.role}</b><span>→ {target?.name||"선택 없음"}</span></div>})}</section>}{error&&<p className="error floating">{error}</p>}</main>;
}
function TargetPicker({players,initial,onSubmit,busy}:{players:Player[];initial:string;onSubmit:(id:string)=>void;busy:boolean}){const[target,setTarget]=useState(initial);useEffect(()=>setTarget(initial),[initial]);return <div className="targets">{players.map(p=><label key={p.id}><input type="radio" name="target" checked={target===p.id} onChange={()=>setTarget(p.id)}/><span>{p.name}</span></label>)}<button className="primary" disabled={!target||busy} onClick={()=>onSubmit(target)}>행동 제출</button></div>}
function RoleCard({role,roomStatus}:{role:string;roomStatus:string}){const[hidden,setHidden]=useState(true),c=byName[role];if(!c)return null;return <button className={`roleFlip ${hidden?"isHidden":""}`} onClick={()=>setHidden(v=>!v)} aria-label={hidden?"내 역할 공개":"내 역할 숨기기"}><span className="roleFlipInner"><span className="card roleBack"><span className="backSeal">CT</span><b>나의 비밀 역할</b><small>눌러서 확인하세요</small></span><span className={`card roleCard ${roomStatus}`}><span className="rolePortrait portrait" style={{backgroundPosition:`${c.index%6*20}% ${Math.floor(c.index/6)*33.333}%`}}/><span className="eyebrow">당신은 {c.team}</span><strong>{c.name}</strong><span>{c.ability}</span><span className="roleGuide"><b>행동 시점</b><span>{c.timing}</span><b>승리 조건</b><span>{c.goal}</span></span><small>눌러서 다시 숨기기</small></span></span></button>}
function NightGuide({day}:{day:number}){const seq=day===1?firstNight:laterNight;return <section className="card nightGuide"><p className="eyebrow">{day===1?"FIRST NIGHT ORDER":"OTHER NIGHT ORDER"}</p><h3>{day===1?"첫째 밤 진행 순서":`${day}일차 밤 진행 순서`}</h3><ol>{seq.map(([title,detail],i)=><li key={`${title}-${i}`}><span>{i+1}</span><div><b>{title}</b><p>{detail}</p></div></li>)}</ol></section>}
function Header(){return <header><div className="mark">CT</div><div><b>CLOCKTOWER</b><span>LIVE</span></div><Link className="wikiLink" href="/wiki">백과사전</Link></header>}
